openapi: 3.0.3
info:
  title: Contract REST API
  version: '1.0'
  description: japan used car contract API
  contact:
    url: 'https://kinto.jp'
    email: kinto@kint.jp
    name: kinto
  license:
    name: Kinto
    url: 'https://kinto.jp'
servers:
  - url: 'http://127.0.0.1:8090/contract'
    description: Local development env
    variables:
      basePath:
        default: contract
paths:
  /v1/user/contract:
    post:
      summary: Contract Register API
      operationId: insertContracts
      responses:
        '200':
          description: OK
      description: 契約申込
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/contract/user/InsertContractCommand.yaml
        description: ''
      tags:
        - UserContract
  /v1/admin/update-commission:
    put:
      summary: Contract Commission Update API
      operationId: updateCommission
      responses:
        '200':
          description: OK
      tags:
        - UserContract
      description: 契約自賠責発行情報更新
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/contract/admin/UpdateCommissionCommand.yaml
  /v1/admin/update-vehicle-info:
    put:
      summary: Contract Vehicle Info Update API
      operationId: updateVehicleInfo
      responses:
        '200':
          description: OK
      description: 契約車両登録情報更新
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/contract/admin/UpdateVehicleInfoCommand.yaml
      tags:
        - AdminContract
  /v1/user/update-dealer:
    post:
      summary: Contract Dealer Update Apply API
      operationId: updateDealer
      responses:
        '200':
          description: OK
      description: 販売店変更申請
      parameters: []
      tags:
        - UserContract
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/application/user/UpdateDealerCommand.yaml
  /v1/admin/approve-dealer:
    put:
      summary: Contract Dealer Update Apply API
      operationId: updateApproveDealer
      responses:
        '200':
          description: OK
      description: 販売店変更承認
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/application/user/UpdateDealerCommand.yaml
      tags:
        - AdminContract
  '/v1//admin/contracts/{contractId}':
    parameters:
      - schema:
          type: string
        name: contractId
        in: path
        required: true
    put:
      summary: ''
      operationId: updateContract
      responses:
        '200':
          description: OK
      description: 契約更新（自賠責発行情報）
      tags:
        - AdminContract
  '/v1/user/contracts/{contractId}':
    parameters:
      - schema:
          type: string
        name: contractId
        in: path
        required: true
    get:
      summary: Contract Detail API
      operationId: getContractDetails
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./schemas/contract/user/ContractDetailsResource.yaml
      description: 契約詳細
      tags:
        - UserContract
      parameters: []
  /v1/user/contracts:
    get:
      summary: Contract Search API
      tags:
        - UserContract
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./schemas/contract/user/ContractListResource.yaml
      operationId: getUserContracts
      description: 契約検索
      parameters: []
  /v1/user/update-using:
    put:
      summary: Contract Vehicle Using Update API
      operationId: updateUsing
      responses:
        '200':
          description: OK
      description: 契約利用開始
      tags:
        - UserContract
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/contract/user/UpdateContractUsingCommand.yaml
  '/user/maintenance/{contractId}':
    parameters:
      - schema:
          type: integer
        name: contractId
        in: path
        required: true
        description: 契約ID
    get:
      summary: Contract Maintenance Detail API
      tags:
        - UserContract
      operationId: getMaintenance
      description: メンテナンス詳細
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./schemas/contract/user/ContractMaintenaceDetailsResource.yaml
components:
  schemas: {}
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      required: false
      schema:
        type: string
        default: application/json; charset=UTF-8
      description: HTTPコンテンツ・タイプ
tags:
  - name: AdminContract
  - name: UserContract
