title: InsertApplicationCommand
type: object
description: 申込データ
properties:
  productId:
    type: integer
    description: 物件ID
  productVersion:
    type: integer
    description: 物件Version
  monthlyFee:
    type: integer
    description: 毎月のお支払い額
  contractType:
    type: integer
    description: |-
      契約区分
      1:個人 2:法人
  contractMonths:
    type: integer
    description: 契約月数
  requestNumberPlateFlag:
    type: boolean
    description: 希望ナンバーフラグ
  requestNumberPlate1:
    type: string
    description: 希望ナンバー_第一希望
    minLength: 0
    maxLength: 32
  requestNumberPlate2:
    type: string
    description: 希望ナンバー_第二希望
    maxLength: 32
    minLength: 0
  bonusFlag:
    type: boolean
    description: ボーナス支払フラグ
  monthlyPlannedDistance:
    type: integer
    description: 月間予定走行距離
  excessDrivingFee:
    type: integer
    description: 超過走行料
  applicationAmount:
    type: integer
    description: 申込金金額
  purchaseDealerChannel:
    type: string
    description: |-
      購入販売店チャネル
      1:TOYOTA; 2:TOYOPET; 3:COROLLA;4:Netz; 5:Mobility;6:LEXUS
    maxLength: 4
    minLength: 0
  purchaseDealerCode:
    type: string
    description: 購入販売店コード
    minLength: 0
    maxLength: 32
  purchaseDealerName:
    type: string
    description: 購入販売店名
    minLength: 0
    maxLength: 32
  purchaseStoreCode:
    type: string
    description: 購入販売店店舗コード
    minLength: 0
    maxLength: 32
  purchaseStoreName:
    type: string
    description: 購入店舗名
    minLength: 0
    maxLength: 32
  purchaseMaintainerChannel:
    type: string
    description: 購入時保守販売店チャネル
    minLength: 0
    maxLength: 32
  purchaseMaintainerCode:
    type: string
    description: 購入時保守販売店コード
    minLength: 0
    maxLength: 32
  purchaseMaintainerName:
    type: string
    description: 購入時保守販売店名
    minLength: 0
    maxLength: 32
  purchaseMaintainerDealerStoreCode:
    type: string
    description: 購入時保守販売店店舗コード
    minLength: 0
    maxLength: 32
  purchaseMaintainerStoreName:
    type: string
    description: 購入時保守店舗名
    minLength: 0
    maxLength: 32
  usingPurposeType:
    type: integer
    description: 主な使用目的
    minimum: 0
    maximum: 4
  usingPurposeLabel:
    type: string
    description: 主な使用目的値ラベル
    maxLength: 100
    minLength: 0
  parkingPostcode:
    type: string
    description: 保管場所郵便番号
    maxLength: 8
    minLength: 0
  parkingPrefecture:
    type: integer
    description: 保管場所都道府県
  parkingCity:
    type: string
    description: 保管場所市区郡町村
    maxLength: 16
    minLength: 0
  parkingAddress:
    type: string
    description: 保管場所丁目・番地
    minLength: 0
    maxLength: 64
  parkingCityKana:
    type: string
    description: 保管場所市区郡町村カナ
    maxLength: 32
    minLength: 0
  parkingAddressKana:
    type: string
    description: 保管場所丁目・番地カナ
    maxLength: 128
    minLength: 0
  drivingLicenseNumber:
    type: string
    description: 運転免許番号
    minLength: 0
    maxLength: 32
  drivingLicenseImgFront:
    type: string
    maxLength: 512
    minLength: 0
  drivingLicenseImgBack:
    type: string
    description: 運転免許画像裏面
    maxLength: 512
    minLength: 0
  personalInfo:
    $ref: ../../common/PersonalInfo.yaml
  companyInfo:
    $ref: ../../common/CompanyInfo.yaml
required:
  - productId
  - productVersion
  - monthlyFee
  - contractType
  - contractMonths
  - requestNumberPlateFlag
  - monthlyPlannedDistance
  - excessDrivingFee
  - applicationAmount
  - purchaseDealerChannel
  - purchaseDealerCode
  - purchaseDealerName
  - purchaseStoreCode
  - purchaseStoreName
  - purchaseMaintainerChannel
  - purchaseMaintainerCode
  - purchaseMaintainerName
  - purchaseMaintainerDealerStoreCode
  - purchaseMaintainerStoreName
  - usingPurposeType
  - usingPurposeLabel
  - parkingPostcode
  - parkingPrefecture
  - parkingCity
  - parkingAddress
  - parkingCityKana
  - parkingAddressKana
  - drivingLicenseNumber
  - drivingLicenseImgFront
  - drivingLicenseImgBack
