title: ApplicationSituationInfo
type: object
description: 申込詳細
properties:
  applicationId:
    type: integer
    description: 申込ID
  contractNumber:
    description: 契約管理番号(TFC設定項目)
    type: string
  contractStatus:
    type: string
    description: 契約ステータス
  contractStatusUpdateDatetime:
    type: string
    format: date-time
    description: 契約ステータス更新日
  agreementDatetime:
    type: string
    format: date-time
    description: 申込規約同意日時
  identificationDatetime:
    type: string
    format: date-time
    description: 本人確認日時
  identificationResult:
    type: integer
    description: '本人確認結果:0:不一致 1:一致'
  identificationPlace:
    type: integer
    description: '確認場所:0：店舗1：自宅  2：その他'
  identificationRsultOther:
    type: string
    description: 本人確認その他確認
  identificationStaffLastName:
    type: string
    description: 本人確認担当者姓
  identificationStaffFirstName:
    type: string
    description: 本人確認担当者名
  creditEntryDatetime:
    type: string
    format: date-time
    description: 与信審査申込日時
  creditResult:
    type: integer
    description: '与信結果:0:NG 1:OK'
  creditDate:
    type: string
    format: date
    description: 与信結果確定日
  creditExpireDate:
    type: string
    format: date
    description: 与信結果有効期限
  contractEntryDatetime:
    type: string
    format: date-time
    description: 本契約申込日時(契約日)
  reasonForDifference:
    type: string
    description: 差異理由
  jpassComment:
    type: string
    description: J-Pass連携コメント
  followMailFlag:
    type: boolean
    description: フォローメール送信フラグ
