title: UpdateApplicationCommand
type: object
description: 審査ステータス
properties:
  contractStatus:
    type: string
    minLength: 0
    maxLength: 32
    description: |-
      契約ステータス
      003:申込内容確認中
      005:審査お見送り
      006:不備ご連絡中
      007:審査承認
  contractNumber:
    type: string
    description: 契約管理番号(TFC設定項目)
    minLength: 0
    maxLength: 32
  contractStatusUpdateDatetime:
    type: string
    description: 契約ステータス更新日
    format: date-time
  agreementDatetime:
    type: string
    description: 申込規約同意日時
    format: date-time
  identificationDatetime:
    type: string
    description: 本人確認日時
    format: date-time
  identificationResult:
    type: integer
    description: "本人確認結果\t\n0：不一致  \n1：一致"
  identificationPlace:
    type: integer
    description: |-
      確認場所
      0：店舗  1：自宅  2：その他
  identificationResultOther:
    type: string
    description: |
      本人確認その他確認
    minLength: 0
    maxLength: 128
  identificationStaffLastName:
    type: string
    minLength: 0
    maxLength: 16
    description: 本人確認担当者姓
  identificationStaffFirstName:
    type: string
    description: 本人確認担当者名
    minLength: 0
    maxLength: 16
  creditEntryDatetime:
    type: string
    format: date-time
    description: 与信審査申込日時
  creditResult:
    type: integer
    description: |-
      与信結果
      0:NG 1:OK
  creditDate:
    type: string
    format: date-time
    description: 与信結果確定日
  creditExpireDate:
    type: string
    format: date-time
    description: 与信結果有効期限
  contractEntryDatetime:
    type: string
    format: date-time
    description: 本契約申込日時(契約日)
  reasonForDifference:
    type: string
    maxLength: 255
    minLength: 0
    description: 差異理由
  jpassComment:
    type: string
    minLength: 0
    maxLength: 255
    description: J-Pass連携コメント
  followMailFlag:
    type: boolean
    description: フォローメール送信フラグ
  comment:
    type: string
    description: コメント
    minLength: 0
    maxLength: 32
required:
  - contractStatus
  - contractNumber
  - contractStatusUpdateDatetime
  - agreementDatetime
  - identificationDatetime
  - identificationResult
  - identificationPlace
  - identificationResultOther
  - identificationStaffLastName
  - identificationStaffFirstName
  - creditEntryDatetime
  - creditResult
  - creditDate
  - creditExpireDate
  - reasonForDifference
  - jpassComment
  - followMailFlag
