description: ''
type: object
x-examples:
  example-1:
    makerName: TOYOTA
    modelName: GRヤリス
    gradeName: RS GAS 1.5L 2WD(4人)
    applicationFee: 2000
    monthlyFee: 2000
    comment1: comment1
    comment2: comment2
    imagesUrl:
      - 'https://www.image.com/01'
      - 'https://www.image.com/02'
      - 'https://www.image.com/03'
    firstRegistrationDate: 2021(R3)
    vehicleRegistrationDate: 2021/01/01
    driveWheelsType: 1
    displacement: 1988
    fuelType: 1
    seatsNumber: 5
    equipments:
      - equipmentClassification: セーフティパッケージ
        equipmentName: ナビ･ETC･パノラミックビューモニター･フロアマットが含まれています
examples: []
properties:
  makerName:
    type: string
    description: メーカー名
  modelName:
    type: string
    description: 車種名
  gradeName:
    type: string
    description: グレード名
  applicationFee:
    type: integer
    description: 申込金
  monthlyFee:
    type: integer
    description: 月額
  comment1:
    type: string
    description: コメント1
  comment2:
    type: string
    description: コメント2
  imagesUrl:
    type: array
    description: 掲載画像URL
    items:
      type: string
  firstRegistrationDate:
    type: string
    description: 年式
  vehicleRegistrationDate:
    type: string
    description: 車両登録年月日
    format: date
  driveWheelsType:
    type: integer
    description: 駆動方式(稼働方式)
  displacement:
    type: integer
    description: 排気量
  fuelType:
    type: integer
    description: 燃料
  seatsNumber:
    type: integer
    description: 乗車定員
  equipments:
    type: array
    uniqueItems: true
    description: 装備
    items:
      $ref: ../EquipmentsInfo.yaml
